config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { minimum: 4 }
  validates :description, presence: true
  validates :description, length: { minimum: 4 }
  
  paginates_per 15
  
  enum category: [ :cooking, :humor, :news ]
  
  scope :search, -> (name) { where("name LIKE :name or description LIKE :name or tags LIKE :name or category = :category", name: '%' + name + '%', category: Page.categories[name.to_sym]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_page, only: [ :show, :edit ]
  before_action :set_pages, only: [ :create, :index ]
  
  def create
  end
  
  def index
  end
  
  def new
    @page = Page.new
  end
  
  private
  
  def find_page
    @page = Page.find(params[:id])
  end
  
  def set_pages
    @pages = Page.search(params[:search].to_s).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", danger: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      unless message == true
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
                concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                concat message 
              end)
      end
    end
    nil
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alert.html.haml
= flash_messages

app/views/layouts/_menu.html.haml
%nav{ class: 'navbar navbar-default navbar-fixed-top', role: 'navigation' }
  %div{ class: 'navbar-header'}
    %button.some{ type: 'button', class: 'navbar-toggle', 'data-toggle': 'collapse', 'data-target': '#bs-example-navbar-collapse-1' }
      %span{ class: 'sr-only' } Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand.some{ href: root_path } 
      = image_tag("logo.png", border: 0, size: '115x30')
  %div{ class: 'collapse navbar-collapse', id: 'bs-example-navbar-collapse-1'}
    // %ul.some{ class: 'nav navbar-nav'}
    //   %li.Test
    //     %a{ href: new_page_path }
    //       New page
    = render 'layouts/search_form'

app/views/layouts/_search_form.html.haml
= form_tag @search, class: 'navbar-form navbar-left', role: 'search' do
  %div{ class: 'form-group' }
    %input.form-control{ name: :search, type: 'text' }
  %button{ type: 'submit', class: 'btn btn-default' }
    search

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RnDSoft
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div.container-fluid
      %br
      %br
      %br
      %div.col-md-8
        = render 'layouts/menu'
        = yield
      %div.col-md-4
        = render 'layouts/alert'

app/views/pages/_form.html.haml
= form_for @page, html: { class: 'form-horizontal', role: 'form' } do |f|

  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputPageName' }
      Name
    %div.col-sm-8
      - if action_name == "show"
        = f.text_field :name, :class => "form-control", disabled: :true
      - else
        = f.text_field :name, :class => "form-control"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputPageDescriprion' }
      Descriprion
    %div.col-sm-8
      - if action_name == "show"
        = f.text_area :description, :class => "form-control", disabled: :true
      - else
        = f.text_area :description, :class => "form-control"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputPageAddressn' }
      Address
    %div.col-sm-8
      - if action_name == "show"
        = f.text_field :address, :class => "form-control", disabled: :true
      - else
        = f.text_field :address, :class => "form-control"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputPageTags' }
      Tags
    %div.col-sm-8
      - if action_name == "show"
        = f.text_area :tags, :class => "form-control", disabled: :true
      - else
        = f.text_area :tags, :class => "form-control"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputPageTags' }
      Category
    %div.col-sm-8
      - if action_name == "show"
        = f.text_field :category, :class => "form-control", disabled: :true
      - else
        = f.select :category, Page.categories.keys.map { |w| [w.humanize, w] }, :class => "form-control"
  %div.form-group
    %label.col-sm-4.control-label
    %div.col-sm-8
      = link_to t('.back'), pages_path, {class: "btn btn-default button" }
      - unless action_name == "show"
        %button.btn.btn-default{ type: "submit button" }
          = t('.submit')

app/views/pages/_page.html.haml
%tr
  %td= page.id
  %td
    = link_to page.name, page_path(page)
  %td= page.description
  %td= page.tags
  %td= page.category

app/views/pages/_page_title.html.haml
%tr
  %th #
  %th
    Name
  %th
    Description
  %th
    Tags
  %th
    Category

app/views/pages/create.html.haml
%table.table.table-striped
  %thead
    = render 'page_title'
  %tbody.tbody-pages
    = render @pages

%br

= paginate @pages, :theme => 'twitter-bootstrap-3',
                   :pagination_class => "pagination-sm"

%br

app/views/pages/edit.html.haml
= render 'form'

app/views/pages/index.html.haml
%table.table.table-striped
  %thead
    = render 'page_title'
  %tbody.tbody-pages
    = render @pages

%br

= paginate @pages, :theme => 'twitter-bootstrap-3',
                   :pagination_class => "pagination-sm"

%br

app/views/pages/new.html.haml
= render 'form'

app/views/pages/show.html.haml
= render 'form'